# report_*: given a list generated by a purrr::safely()- or
# purrr:quietly()-wrapped function, return a vector listing the present
# components of the list:
# safely: result (R), error (E)
# quietly: result (R), warning (W), message (M), output (O)
# absent components are replaced with an underscore (_)

#' @export
report_safely = function(x) {
  map(x,
    ~ paste0(
      if (is.null(.$result))                            '_' else 'R',
      if (is.null(.$error) | is_empty(.$error$message)) '_' else 'E')) %>%
  as_vector() %>% structure(class = "report_safely")
}

#' @export
report_quietly = function(x) {
  map(x,
      ~ paste0(
      if (is.null(.$result))                            '_' else 'R',
      if (is.null(.$output) | is_empty(.$output))       '_' else 'O',
      if (is.null(.$message) | is_empty(.$message))     '_' else 'M',
      if (is.null(.$warning) | is_empty(.$warning))     '_' else 'W')) %>%
  as_vector() %>% structure(class = "report_quietly")
}

# TODO - do i need to define c.XXX and `[.XXX`?
# ref: https://cran.rstudio.com/web/packages/tibble/vignettes/extending.html

# format and print functions are pretty plain

#' @export
format.report_safely = function(x, ...) {
  format(x, justify = "left")
}

#' @export
format.report_quietly = function(x, ...) {
  format(x, justify = "left")
}

#' @export
print.report_safely = function(x, ...) {
  cat(format(x), sep = '\n')
  invisible(x)
}

#' @export
print.report_quietly = function(x, ...) {
  cat(format(x), sep = '\n')
  invisible(x)
}

# override column headers
#' @importFrom pillar type_sum
#' @export
type_sum.report_safely <- function(x) {
  "collateral"
}

#' @importFrom pillar type_sum
#' @export
type_sum.report_quietly <- function(x) {
  "collateral"
}
